python3 src/main.py \
    --dataset 'Singapore_defense'\
    --num_mapping_layers 1 \
    --map_dim 768 \
    --fusion align \
    --num_pre_output_layers 3 \
    --drop_probs 0.2 0.4 0.1 \
    --gpus '0' \
    --batch_size 10 \
    --lr 0.00013 \
    --max_epochs 25 \
    --name 'text-inv-comb' \
    --pretrained_model 'harmeme_text-inv-comb_best.ckpt' \
    --reproduce f \
    --pretrained_proj_weights t \
    --freeze_proj_layers t \
    --comb_proj t \
    --comb_fusion align \
    --convex_tensor f \
    --phi_inv_proj t \
    --text_inv_proj t \
    --post_inv_proj t \
    --enh_text t \
    --phi_freeze t \
    --fast_process f \
